import logging

from core.algo import TradeMethod

BINANCE_API_KEY = 'FbtgTH5TAgpggxR4ltDMMjQaCLpVG2AHmzNbtwUYKiInUdbqdVnO79AXHAKnsw5X'
BINANCE_SECRET_KEY = 'g78DnJ3VMB4TZPt3rVppf5lPKqWj9Ei0EMZjyw4IktoAmv5LsBqmVvWZsxhFZbRZ'

LOG_LEVEL = logging.DEBUG

SYMBOL = 'ETHUSDT'
LAMBDA = 0.0147
COMMISSION_RATE = 0.0005
TRADE_METHOD = TradeMethod.TF

